### PR TITLE
Features/i6 view rencana

### PR DESCRIPTION
**Pull request by gejimayu**
ddddddddddddddddddd

### CODE REVIEW

**Comment by gejimayu** [comment]
Error mlu nih travisnya napa ya ???

**Comment by gejimayu** [comment]
aso

**Comment by keychera** [comment]
@gejimayu the test still fails locally, gi. do run all the test first before pushing

**Comment by gejimayu** [comment]
Yes key , can u please debug it? I think the error lies in the unit test,
not in the program bcs the program works fine.

**Pull request closed without merging**
