### PR TITLE
[WIP] Fix bugs in test file

### PR DESCRIPTION
**Pull request by rayandrew**
@deryrahman @keychera this push is error-clean, but still finding some failed build in TravisCI.

Don't approved yet, still finding the real bug of gradle test

### CODE REVIEW

**Comment by rayandrew** [comment]
really i don't know the bug. 
i think it's because the file name is too long.
but in this branch, checks all have passed.

@deryrahman @keychera

**Comment by deryrahman** [comment]
@rayandrews hmm, seems weird. ok, will be merge soon

**Comment by deryrahman** [comment]
wew, mistake

**Comment by deryrahman** [comment]
@rayandrews seems weird. ok, will be merge soon

**Review by deryrahman — APPROVED** [review]

**Pull request merged**
